
# Q4

In [1]:
import numpy as np

In [ ]:
x=int(input('1.Two Dimensional\n''2.One Dimensional\n'))

In [ ]:
if(x==1):
    n=int(input("Enter the x-dimension of 2D array: "))
    m=int(input("Enter the y-dimension of 2D array: "))
    
    c=int(input("Select how do you want to fill the array with: \n"'1. With Zeros\n''2. With Ones\n''3. With random values\n''4. With Diagonal Matrix\n'))
    if(c==1):
        a=np.zeros((n,m))
    if(c==2):
        a=np.ones((n,m))
    if(c==3):
        a=np.random.randint(100,size=(n,m))
    if(c==4):
        a=np.eye(n,m,k=0)
    print(a)

In [ ]:
if(x==2):
    p=int(input("Enter the size of 1D array: "))
    q=int(input("Select how do you want to fill the array with: \n"'1. With Zeros\n''2. With Ones\n''3. With random values\n''4.Diagonal Matrix\n'))
    if(q==1):
        a=np.zeros((p))
    if(q==2):
        a=np.ones((p))
    if(q==3):
        a=np.random.randint(100,size=(p))
    if(q==4):
        a=np.eye(p,k=0)
    print(a)

In [ ]:

np.eye(4,3,k=1)

# Q5

In [2]:
import pandas as pd,csv

In [ ]:
l=np.loadtxt('iris.csv',delimiter=',',dtype='str')
l

In [ ]:
l.shape

In [ ]:
l.shape[0]

In [ ]:
l.shape[1]

In [ ]:
l[0]

In [ ]:
file=np.savetxt('TEXT.txt',l,delimiter=',',fmt='%s')

In [ ]:
from datetime import datetime
import time

In [ ]:
a=int(input("Enter the number of rows of matrix: "))
b=int(input("Enter the number of columns of matrix: "))
c=int(input('1. Addition\n''2. Substraction\n''3. Multiplication\n'))
p=np.random.randint(10,size=(a,b))
q=np.random.randint(10,size=(a,b))
if(c==1):
    x=time.time()
    j=p+q
    y=time.time()
    print(x)
    print(y)
    print('Time taken: ',y-x)
    r=[[p[i,j]+q[i,j] for i in range(a)] for j in range(b)]
    z=time.time()
    print("Time taken in for loop: ",z-y)
if(c==2):
    x=time.time()
    j=p-q
    y=time.time()
    print(x)
    print(y)
    print('Time taken: ',y-x)
    r=[[p[i,j]+q[i,j] for i in range(a)] for j in range(b)]
    z=time.time()
    print("Time taken in for loop: ",z-y)
if(c==3):
    x=time.time()
    result = [[sum(p * q for a, b in zip(p_row, q_col)) 
                        for q_col in zip(*q)]
                                for p_row in p]
  #  for r in result:
    print(result)
    y=time.time()
    print(x)
    print(y)
    print('Time Taken: ',y-x)
print("1: \n\n",p)
print("2: \n\n",q)
u=int(input('Choose one matrix: 1 or 2: '))
if(u==1):
    i=int(input("Enter the x-axis: "))
    o=int(input("Enter the y-axix: "))
    print(p[i,o])
if(u==2):
    i=int(input("Enter the x-axis: "))
    o=int(input("Enter the y-axix: "))
    print(q[i,o])

In [ ]:
print(np.dot(p,q))

# Q7

In [3]:
a=int(input("Enter the x-axis size of matrix: "))
b=int(input("Enter the y-axis size of matrix: "))
x=np.zeros(shape=(a,b))
print(x)
print("Enter the values of matrix: \n")
for i in range(a):
    for j in range(b):
            x[i,j]=(input(x[i,j]))
print('Our Matrix is: \n',x)
y=abs(x)
print('Absolute matrix is: \n',y)



Enter the x-axis size of matrix: 2
Enter the y-axis size of matrix: 2
[[0. 0.]
 [0. 0.]]
Enter the values of matrix: 

0.05
0.0-2
0.03
0.06
Our Matrix is: 
 [[ 5. -2.]
 [ 3.  6.]]
Absolute matrix is: 
 [[5. 2.]
 [3. 6.]]


In [4]:

print(x)
l=[]
c=int(input("Choose which you want to remove \n1.Row \n2.Column\n"))
if(c==1):
    m=int(input("Enter the number of rows to delete: "))
    print("Enter the locations: ")
    for i in range(m):
        ele=int(input())
        l.append(ele)
        x=np.delete(x,l,0)
    print(x)
if(c==2):
    n=int(input("Enter the number of columns to delete: "))
    print("Enter the locations: ")
    for i in range(n):
        ele=int(input())
        l.append(ele)
        x=np.delete(x,l,1)
    print(x)

[[ 5. -2.]
 [ 3.  6.]]
Choose which you want to remove 
1.Row 
2.Column
1
Enter the number of rows to delete: 1
Enter the locations: 
1
[[ 5. -2.]]


In [6]:
print(x)
print("Maximum of matrix is: ")
x.max()
q=int(input('Enter the row number to find the maximum & minimum: '))
print('Max: ',np.max(x[q,:]))
print('Min: ',np.min(x[q,:]))
w=int(input('Enter the column number to find the maximum & minimum: '))
print('Max: ',np.max(x[:,w]))
print('Min: ',np.min(x[:,w]))

[[ 5. -2.]]
Maximum of matrix is: 
Enter the row number to find the maximum & minimum: 0
Max:  5.0
Min:  -2.0
Enter the column number to find the maximum & minimum: 0
Max:  5.0
Min:  5.0


In [7]:
print('Sum is: ',np.sum(x))

Sum is:  3.0


In [8]:
q=int(input('Enter the row number to find the maximum & minimum: '))
print('Row-wise: ',np.sum(x[q,:]))
print('Column-wise: ',np.sum(x[:,q]))

Enter the row number to find the maximum & minimum: 0
Row-wise:  3.0
Column-wise:  5.0


In [ ]:
df=pd.read_csv('FuelConsumptionDataset.csv')

In [ ]:
x=csv.reader('FuelConsumptionDataset.csv')